name: Build artifacts

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: 'main'
      - uses: actions/setup-java@v5.7.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build code
        # This ensures that there are no compile time problems with this PR
        run: mvn -B clean install
