name: Update data

on:
  schedule:
    - cron: '0 7 * * *'

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "github"
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - id: report
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn clean install exec:java -Pgithub
          ./load-run-logs.sh
          ./load-retried-prs.sh
          if ( ! git diff --exit-code &>/dev/null ); then 
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add --all 
            git commit -m "Updated data"
            git push
          fi
  deploy:
    uses: ./.github/workflows/pages.yml
    needs: [update]
